#ifndef SHARED_DEFINES_HEADER

#define RENDERER_USING_BINDLESS 1
// #define RENDERER_DEBUG 1
#define BINDING_DRAW_COMMAND 18
#define BINDING_MATERIAL     10
#define BINDING_CAMERA       2

#define SHARED_DEFINES_HEADER

#endif // SHARED_DEFINES_HEADER
